### PR TITLE
Add filter for altitude

### PR DESCRIPTION
**Pull request by emctoo**

### CODE REVIEW

**Comment by emctoo** [comment]
@liuyuntian and I think we should make a working version first. We are now exploring the way to implement this as a plugin. You are right, this is definitly not the a plugin.

We should make this as a draft.

**Comment by xoolive** [comment]
Great, I will check ASAP, but let's leave the PR open and think about the plugin part!

**Comment by xoolive** [comment]
@liuyuntian may I ask again for the formatting settings? :pray:

**Comment by xoolive** [comment]
Coming back to our topic (thinking aloud), I see basically plugins as, extensively:

- frontend:
	- extra css content (new file)
	- extra js content (new file)
	- extra html content: should we say we extend a template and get a new page? or maybe there are also default places where we could add things: Leaflet objects/layers, filters, extra elements in the header, in the sidebar, etc. (to be defined)
	
- backend:
	- a python function adding new endpoints to the engine

We could for a start just put as many folders (plugins) as we want in a `plugins` folder, with code looking like

```python
# Syntax to be adapted of course!
import tangram as t

class Plugin(t.plugins):  # with a smart `__init_subclass__` for automatic registration
	CSS_FILE = ""  # or a list?
	JS_FILE = ""
	# etc.

	@t.endpoints.new("/plugin_one")  # something related to the fastapi (that's just me hallucinating here)
    await def super_endpoint(self):
		return {'reply': 'yeah!'}

    @t.leaflet.new_layer("sigmet")
	await def return_sigmets(self):
        return a_fun_geojson

	@t.sidebar.append()
	def new_element(self):
        return element

```

Then if there's a page to click for activating/deactivating (or a config file) that's should be flexible enough for a start?

Any thoughts?

@emctoo @junzis

**Comment by xoolive** [comment]
Also just rebased/reformatted manually to reduce this PR to a minimal set of changes (easier to work out when doing plugins)

**Comment by junzis** [comment]
Hi guys, I just got time to have a look at this. Yes, the proposed way of defining a plugin is fine to me.

I would also allow python only plugins that requires no extra css or js. This way users can use pre-defined shapes and existing UI elements to visualize the results they want. 

Perhaps, except aircraft themselves, all visualizations for other data types should be implemented in this "plugin" way already?

**Comment by xoolive** [comment]
Yes the way I see it, if a field is not defined, nothing is added.

**Pull request closed without merging**
